# Generated by Django 5.1.4 on 2025-01-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_department_doctor_department_prescription_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='occupied_beds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
